### ISSUE TITLE
Team-Naboos

### ISSUE THREAD

**Issue by StarSheriff2** [alexisbec/members-only#1]

**Comment by jcy2704** [comment]
**Application layout**
- Move if statements to application helper

**Post controller**
- Remove unnecessary methods (edit, update, destroy, and others) and unnecessary JSON code

**Comment by marcelomaidden** [comment]
First of all congratulations on your project, you've done a great job so far. 
I have some suggestions of improvements that I will mention below:
- Routes: the Odin requirements say to allow only [:new, :create, :index] for the Post
- In your Posts Controller there are some JSON returns added by default when you use scaffolding
- Remove conditionals inside the views and move to helpers
- On the User model you used author as a field, it can be confusing for people who are reviewing your project
